### ISSUE TITLE
"Unable to use the drive" error

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/minio_ynh#33]
### Describe the bug

After upgrading to v2022.11.11~ynh1, the service does not start, returning the following error:

```
ERROR Unable to use the drive /home/yunohost.app/minio: Drive /home/yunohost.app/minio: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified
```

Instructions over at https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html are pretty massive. I guess they should be automated.

### Context

- Hardware: VPS
- YunoHost version: 11.1.0.2 testing
- I have access to my server: ssh/webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: testing branch
- Current package version: v2022.11.11~ynh1

**Comment by fflorent** [comment]
Even when installing the app from scratch I get a `502 Bad Gateway` and the logs show the same error about the wrong backend type

**Comment by Limezy** [comment]
Oops, that's right. MinIO did a migration and I need to find a way to update accordingly... 
I'm very busy, any help is very much welcome !

**Comment by Limezy** [comment]
Wow, I've spent a bit of time on it, and this seems to be very complicated... 
It's a bit harsh from the MinIO team to deprecate this without real warning, without proper migration automation, and even worse, not allowing downgrading (I've tried a --force upgrade to previous version of the package ...)

**Comment by Limezy** [comment]
OK, I think I have found an interesting middle ground : I was able to recreate an identitcal and working bucket with all objects untouched using a mirror mc command. I think it's doable to automate this in the upgrade process -> to be added to #34 
The only loss is the bucket access policy (in Outline case, for instance, I had to set again the bucket policy to "public"). 
This would be extremely hard to automate as it would need running two instances of MinIO (one old, one new...), then remove the old one, then rename the new one... 

I think it's an acceptable thing for users to get warned during the upgrade that they should log into the web UI and change back their buckets policy. It's also something that can be done within the next upgrade of the app using MinIO as an internal layer. In Outline case, for instance, I can make sure that the next upgrade will automatically force the bucket policy to "public", so there will be no manual action required from the user.

@fflorent @tituspijean what do you think ?
Do you actually know any Yunohost app using MinIO, other than Outline ?

**Comment by Limezy** [comment]
I have started working on a migration script within the upgrade routine.
It seems to work, I still need a bit of testing before merging on top of @fflorent's PR #34

**Comment by Limezy** [comment]
https://github.com/Limezy/minio_ynh/tree/tests-migration-fs
You can follow the progress here
